DROP TABLE BOOKS CASCADE CONSTRAINTS;

CREATE TABLE BOOKS(
	BOOK_ID NUMBER,
	BOOK_NAME VARCHAR2(15) NOT NULL,
	CONSTRAINT BK_BOOK_ID_PK PRIMARY KEY ( BOOK_ID )
);

INSERT INTO BOOKS VALUES(1,'HTML 5');
INSERT INTO BOOKS VALUES(2,'CSS 3');
INSERT INTO BOOKS VALUES(3,'Java Script');
INSERT INTO BOOKS VALUES(4,'Angular 5');

SELECT * FROM BOOKS;
