server:
  port: 7701

spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb+srv://pink58972:58972pink@cluster0.yk37mf1.mongodb.net/PingPracticeDB?retryWrites=true&w=majority
      database: PingPracticeDB
#      port: 27017
#      auto-index-creation: true
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER
#    servlet:
#      path: /customer-service # // localhost:7700/customer-service/user

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#security:
#  jwt:
#    token:
#      key: PingPractice